# Generated by Django 4.2.6 on 2023-10-05 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('final', models.DateTimeField()),
                ('valido', models.BooleanField(default=True)),
                ('escala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escala.escala')),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='funcionario.funcionario')),
            ],
        ),
    ]
