<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-05 04:22
=======
# Generated by Django 4.2.6 on 2023-10-05 03:53
>>>>>>> e42a37fde7120131945d656b212baca2626456c8

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('codigo', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
<<<<<<< HEAD
                ('data_comeco', models.DateField()),
                ('data_final', models.DateField()),
=======
                ('data_comeco', models.DateField(default=datetime.datetime(2023, 10, 5, 0, 53, 33, 826821))),
                ('data_final', models.DateField(default=datetime.datetime(2023, 10, 5, 0, 53, 33, 826821))),
>>>>>>> e42a37fde7120131945d656b212baca2626456c8
            ],
        ),
    ]
