# Generated by Django 4.2.6 on 2023-10-05 11:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('codigo', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_comeco', models.DateField()),
                ('data_final', models.DateField()),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
            },
        ),
        migrations.CreateModel(
            name='FUNCIONARIOS_ESCALA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escala.escala')),
                ('funcionarios', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='funcionario.funcionario')),
            ],
            options={
                'verbose_name': 'FUNCIONARIOS_ESCALA',
                'verbose_name_plural': 'FUNCIONARIOS_ESCALAs',
            },
        ),
    ]
