# Generated by Django 4.2.6 on 2023-10-05 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='data_comeco',
            field=models.DateField(default=datetime.datetime(2023, 10, 5, 1, 12, 3, 901602)),
        ),
        migrations.AlterField(
            model_name='escala',
            name='data_final',
            field=models.DateField(default=datetime.datetime(2023, 10, 5, 1, 12, 3, 901602)),
        ),
    ]
