# Generated by Django 4.2.6 on 2023-10-05 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
        ('escala', '0002_alter_escala_data_comeco_alter_escala_data_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escala',
            name='data_comeco',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='escala',
            name='data_final',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='MEDICOS_ESCALA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escala.escala')),
                ('medicos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='funcionario.funcionario')),
            ],
        ),
    ]
