# Generated by Django 4.2.6 on 2023-10-05 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
        ('escala', '0003_alter_escala_data_comeco_alter_escala_data_final_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FUNCIONARIOS_ESCALA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'FUNCIONARIOS_ESCALA',
                'verbose_name_plural': 'FUNCIONARIOS_ESCALAs',
            },
        ),
        migrations.AlterModelOptions(
            name='escala',
            options={'verbose_name': 'Escala', 'verbose_name_plural': 'Escalas'},
        ),
        migrations.DeleteModel(
            name='MEDICOS_ESCALA',
        ),
        migrations.AddField(
            model_name='funcionarios_escala',
            name='escala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escala.escala'),
        ),
        migrations.AddField(
            model_name='funcionarios_escala',
            name='funcionarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='funcionario.funcionario'),
        ),
    ]
