<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-05 04:22
=======
# Generated by Django 4.2.6 on 2023-10-05 03:53
>>>>>>> e42a37fde7120131945d656b212baca2626456c8

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('pontuacao', models.IntegerField()),
<<<<<<< HEAD
                ('Funcao', models.CharField(max_length=255)),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='escala.escala')),
=======
                ('funcao', models.CharField(max_length=255)),
>>>>>>> e42a37fde7120131945d656b212baca2626456c8
            ],
        ),
    ]
