<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-05 12:10
=======
# Generated by Django 4.2.6 on 2023-10-05 11:29
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('pontuacao', models.IntegerField()),
                ('funcao', models.CharField(max_length=255)),
            ],
        ),
    ]
